version: '3'

services:
  database:
    image: postgres
    environment:
        POSTGRES_PASSWORD: pass
        POSTGRES_USER: user
        POSTGRES_DB: users
    ports:
      - "5432:5432"

  database-mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: users
    ports:
      - "3307:3306"