name: Test Coverage

on:
  push:
    branches:
      - main
    paths:
      - "server/**"

jobs:
  hoge:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: |
          rate=10
          echo $rate
